CREATE TABLE IF NOT EXISTS posts (
    post_id BIGINT NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    image_name TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);