CREATE TABLE IF NOT EXISTS boosts (
    boost_id BIGINT UNIQUE PRIMARY KEY AUTO_INCREMENT,
    post_id BIGINT NOT NULL,
    views_estimated_count INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    FOREIGN KEY (post_id) REFERENCES posts(post_id)
);